version: '3.4'
services:
  Envelopes1_CloseCondition:
    command: run_backtest -v
    build:
      context: ../../..
      target: eurusd-2018
    image: ea31337:eurusd-2018
    volumes:
    - ./sets:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results/EURUSD:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SETFILE: /opt/sets/EURUSD/EA31337-Envelopes1_CloseCondition.set
      TEST_REPORT_NAME: EA31337-Envelopes1_CloseCondition
      SET_PARAMS: Envelopes1_CloseCondition
      RUN_ON_SUCCESS: input_copy Envelopes1_CloseCondition "$${SETFILE}" /opt/advanced/ea-input.mqh
      BT_DEST: /opt/_results/EURUSD
  Envelopes5_CloseCondition:
    command: run_backtest -v
    build:
      context: ../../..
      target: eurusd-2018
    image: ea31337:eurusd-2018
    volumes:
    - ./sets:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results/EURUSD:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SETFILE: /opt/sets/EURUSD/EA31337-Envelopes5_CloseCondition.set
      TEST_REPORT_NAME: EA31337-Envelopes5_CloseCondition
      SET_PARAMS: Envelopes5_CloseCondition
      RUN_ON_SUCCESS: input_copy Envelopes5_CloseCondition "$${SETFILE}" /opt/advanced/ea-input.mqh
      BT_DEST: /opt/_results/EURUSD
  Envelopes15_CloseCondition:
    command: run_backtest -v
    build:
      context: ../../..
      target: eurusd-2018
    image: ea31337:eurusd-2018
    volumes:
    - ./sets:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results/EURUSD:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SETFILE: /opt/sets/EURUSD/EA31337-Envelopes15_CloseCondition.set
      TEST_REPORT_NAME: EA31337-Envelopes15_CloseCondition
      SET_PARAMS: Envelopes15_CloseCondition
      RUN_ON_SUCCESS: input_copy Envelopes15_CloseCondition "$${SETFILE}" /opt/advanced/ea-input.mqh
      BT_DEST: /opt/_results/EURUSD
  Envelopes30_CloseCondition:
    command: run_backtest -v
    build:
      context: ../../..
      target: eurusd-2018
    image: ea31337:eurusd-2018
    volumes:
    - ./sets:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results/EURUSD:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SETFILE: /opt/sets/EURUSD/EA31337-Envelopes30_CloseCondition.set
      TEST_REPORT_NAME: EA31337-Envelopes30_CloseCondition
      SET_PARAMS: Envelopes30_CloseCondition
      RUN_ON_SUCCESS: input_copy Envelopes30_CloseCondition "$${SETFILE}" /opt/advanced/ea-input.mqh
      BT_DEST: /opt/_results/EURUSD
