version: '3.4'
services:
  Envelopes1_OpenCondition1:
    command: run_backtest -v
    build:
      context: ../../..
      target: eurusd-2018
    image: ea31337:eurusd-2018
    volumes:
    - ./sets:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results/EURUSD:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SETFILE: /opt/sets/EURUSD/EA31337-Envelopes1_OpenCondition1.set
      TEST_REPORT_NAME: EA31337-Envelopes1_OpenCondition1
      SET_PARAMS: Envelopes1_OpenCondition1
      RUN_ON_SUCCESS: input_copy Envelopes1_OpenCondition1 "$${SETFILE}" /opt/advanced/ea-input.mqh
      BT_DEST: /opt/_results/EURUSD
  Envelopes5_OpenCondition1:
    command: run_backtest -v
    build:
      context: ../../..
      target: eurusd-2018
    image: ea31337:eurusd-2018
    volumes:
    - ./sets:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results/EURUSD:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SETFILE: /opt/sets/EURUSD/EA31337-Envelopes5_OpenCondition1.set
      TEST_REPORT_NAME: EA31337-Envelopes5_OpenCondition1
      SET_PARAMS: Envelopes5_OpenCondition1
      RUN_ON_SUCCESS: input_copy Envelopes5_OpenCondition1 "$${SETFILE}" /opt/advanced/ea-input.mqh
      BT_DEST: /opt/_results/EURUSD
  Envelopes15_OpenCondition1:
    command: run_backtest -v
    build:
      context: ../../..
      target: eurusd-2018
    image: ea31337:eurusd-2018
    volumes:
    - ./sets:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results/EURUSD:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SETFILE: /opt/sets/EURUSD/EA31337-Envelopes15_OpenCondition1.set
      TEST_REPORT_NAME: EA31337-Envelopes15_OpenCondition1
      SET_PARAMS: Envelopes15_OpenCondition1
      RUN_ON_SUCCESS: input_copy Envelopes15_OpenCondition1 "$${SETFILE}" /opt/advanced/ea-input.mqh
      BT_DEST: /opt/_results/EURUSD
  Envelopes30_OpenCondition1:
    command: run_backtest -v
    build:
      context: ../../..
      target: eurusd-2018
    image: ea31337:eurusd-2018
    volumes:
    - ./sets:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results/EURUSD:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SETFILE: /opt/sets/EURUSD/EA31337-Envelopes30_OpenCondition1.set
      TEST_REPORT_NAME: EA31337-Envelopes30_OpenCondition1
      SET_PARAMS: Envelopes30_OpenCondition1
      RUN_ON_SUCCESS: input_copy Envelopes30_OpenCondition1 "$${SETFILE}" /opt/advanced/ea-input.mqh
      BT_DEST: /opt/_results/EURUSD
  Envelopes1_OpenCondition2:
    command: run_backtest -v
    build:
      context: ../../..
      target: eurusd-2018
    image: ea31337:eurusd-2018
    volumes:
    - ./sets:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results/EURUSD:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SETFILE: /opt/sets/EURUSD/EA31337-Envelopes1_OpenCondition2.set
      TEST_REPORT_NAME: EA31337-Envelopes1_OpenCondition2
      SET_PARAMS: Envelopes1_OpenCondition2
      RUN_ON_SUCCESS: input_copy Envelopes1_OpenCondition2 "$${SETFILE}" /opt/advanced/ea-input.mqh
      BT_DEST: /opt/_results/EURUSD
  Envelopes5_OpenCondition2:
    command: run_backtest -v
    build:
      context: ../../..
      target: eurusd-2018
    image: ea31337:eurusd-2018
    volumes:
    - ./sets:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results/EURUSD:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SETFILE: /opt/sets/EURUSD/EA31337-Envelopes5_OpenCondition2.set
      TEST_REPORT_NAME: EA31337-Envelopes5_OpenCondition2
      SET_PARAMS: Envelopes5_OpenCondition2
      RUN_ON_SUCCESS: input_copy Envelopes5_OpenCondition2 "$${SETFILE}" /opt/advanced/ea-input.mqh
      BT_DEST: /opt/_results/EURUSD
  Envelopes15_OpenCondition2:
    command: run_backtest -v
    build:
      context: ../../..
      target: eurusd-2018
    image: ea31337:eurusd-2018
    volumes:
    - ./sets:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results/EURUSD:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SETFILE: /opt/sets/EURUSD/EA31337-Envelopes15_OpenCondition2.set
      TEST_REPORT_NAME: EA31337-Envelopes15_OpenCondition2
      SET_PARAMS: Envelopes15_OpenCondition2
      RUN_ON_SUCCESS: input_copy Envelopes15_OpenCondition2 "$${SETFILE}" /opt/advanced/ea-input.mqh
      BT_DEST: /opt/_results/EURUSD
  Envelopes30_OpenCondition2:
    command: run_backtest -v
    build:
      context: ../../..
      target: eurusd-2018
    image: ea31337:eurusd-2018
    volumes:
    - ./sets:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results/EURUSD:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SETFILE: /opt/sets/EURUSD/EA31337-Envelopes30_OpenCondition2.set
      TEST_REPORT_NAME: EA31337-Envelopes30_OpenCondition2
      SET_PARAMS: Envelopes30_OpenCondition2
      RUN_ON_SUCCESS: input_copy Envelopes30_OpenCondition2 "$${SETFILE}" /opt/advanced/ea-input.mqh
      BT_DEST: /opt/_results/EURUSD
