version: '3.4'
services:
  MACD1_CloseCondition:
    command: run_backtest -v
    build:
      context: ../../..
      target: eurusd-2018
    image: ea31337:eurusd-2018
    volumes:
    - ./sets:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results/EURUSD:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SETFILE: /opt/sets/EURUSD/EA31337-MACD1_CloseCondition.set
      TEST_REPORT_NAME: EA31337-MACD1_CloseCondition
      SET_PARAMS: MACD1_CloseCondition
      RUN_ON_SUCCESS: input_copy MACD1_CloseCondition "$${SETFILE}" /opt/advanced/ea-input.mqh
      BT_DEST: /opt/_results/EURUSD
  MACD5_CloseCondition:
    command: run_backtest -v
    build:
      context: ../../..
      target: eurusd-2018
    image: ea31337:eurusd-2018
    volumes:
    - ./sets:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results/EURUSD:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SETFILE: /opt/sets/EURUSD/EA31337-MACD5_CloseCondition.set
      TEST_REPORT_NAME: EA31337-MACD5_CloseCondition
      SET_PARAMS: MACD5_CloseCondition
      RUN_ON_SUCCESS: input_copy MACD5_CloseCondition "$${SETFILE}" /opt/advanced/ea-input.mqh
      BT_DEST: /opt/_results/EURUSD
  MACD15_CloseCondition:
    command: run_backtest -v
    build:
      context: ../../..
      target: eurusd-2018
    image: ea31337:eurusd-2018
    volumes:
    - ./sets:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results/EURUSD:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SETFILE: /opt/sets/EURUSD/EA31337-MACD15_CloseCondition.set
      TEST_REPORT_NAME: EA31337-MACD15_CloseCondition
      SET_PARAMS: MACD15_CloseCondition
      RUN_ON_SUCCESS: input_copy MACD15_CloseCondition "$${SETFILE}" /opt/advanced/ea-input.mqh
      BT_DEST: /opt/_results/EURUSD
  MACD30_CloseCondition:
    command: run_backtest -v
    build:
      context: ../../..
      target: eurusd-2018
    image: ea31337:eurusd-2018
    volumes:
    - ./sets:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results/EURUSD:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SETFILE: /opt/sets/EURUSD/EA31337-MACD30_CloseCondition.set
      TEST_REPORT_NAME: EA31337-MACD30_CloseCondition
      SET_PARAMS: MACD30_CloseCondition
      RUN_ON_SUCCESS: input_copy MACD30_CloseCondition "$${SETFILE}" /opt/advanced/ea-input.mqh
      BT_DEST: /opt/_results/EURUSD
