version: '3.4'
services:
  Fractals1_CloseCondition:
    command: run_backtest -v
    build:
      context: ../../..
      target: eurusd-2018
    image: ea31337:eurusd-2018
    volumes:
    - ./sets:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results/EURUSD:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SETFILE: /opt/sets/EURUSD/EA31337-Fractals1_CloseCondition.set
      TEST_REPORT_NAME: EA31337-Fractals1_CloseCondition
      SET_PARAMS: Fractals1_CloseCondition
      RUN_ON_SUCCESS: input_copy Fractals1_CloseCondition "$${SETFILE}" /opt/advanced/ea-input.mqh
      BT_DEST: /opt/_results/EURUSD
  Fractals5_CloseCondition:
    command: run_backtest -v
    build:
      context: ../../..
      target: eurusd-2018
    image: ea31337:eurusd-2018
    volumes:
    - ./sets:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results/EURUSD:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SETFILE: /opt/sets/EURUSD/EA31337-Fractals5_CloseCondition.set
      TEST_REPORT_NAME: EA31337-Fractals5_CloseCondition
      SET_PARAMS: Fractals5_CloseCondition
      RUN_ON_SUCCESS: input_copy Fractals5_CloseCondition "$${SETFILE}" /opt/advanced/ea-input.mqh
      BT_DEST: /opt/_results/EURUSD
  Fractals15_CloseCondition:
    command: run_backtest -v
    build:
      context: ../../..
      target: eurusd-2018
    image: ea31337:eurusd-2018
    volumes:
    - ./sets:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results/EURUSD:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SETFILE: /opt/sets/EURUSD/EA31337-Fractals15_CloseCondition.set
      TEST_REPORT_NAME: EA31337-Fractals15_CloseCondition
      SET_PARAMS: Fractals15_CloseCondition
      RUN_ON_SUCCESS: input_copy Fractals15_CloseCondition "$${SETFILE}" /opt/advanced/ea-input.mqh
      BT_DEST: /opt/_results/EURUSD
  Fractals30_CloseCondition:
    command: run_backtest -v
    build:
      context: ../../..
      target: eurusd-2018
    image: ea31337:eurusd-2018
    volumes:
    - ./sets:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results/EURUSD:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SETFILE: /opt/sets/EURUSD/EA31337-Fractals30_CloseCondition.set
      TEST_REPORT_NAME: EA31337-Fractals30_CloseCondition
      SET_PARAMS: Fractals30_CloseCondition
      RUN_ON_SUCCESS: input_copy Fractals30_CloseCondition "$${SETFILE}" /opt/advanced/ea-input.mqh
      BT_DEST: /opt/_results/EURUSD
