version: '3.4'
services:
  MA1_CloseCondition:
    command: run_backtest -v
    build:
      context: ../../..
      target: eurusd-2018
    image: ea31337:eurusd-2018
    volumes:
    - ./sets:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results/EURUSD:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SETFILE: /opt/sets/EURUSD/EA31337-MA1_CloseCondition.set
      TEST_REPORT_NAME: EA31337-MA1_CloseCondition
      SET_PARAMS: MA1_CloseCondition
      RUN_ON_SUCCESS: input_copy MA1_CloseCondition "$${SETFILE}" /opt/advanced/ea-input.mqh
      BT_DEST: /opt/_results/EURUSD
  MA5_CloseCondition:
    command: run_backtest -v
    build:
      context: ../../..
      target: eurusd-2018
    image: ea31337:eurusd-2018
    volumes:
    - ./sets:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results/EURUSD:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SETFILE: /opt/sets/EURUSD/EA31337-MA5_CloseCondition.set
      TEST_REPORT_NAME: EA31337-MA5_CloseCondition
      SET_PARAMS: MA5_CloseCondition
      RUN_ON_SUCCESS: input_copy MA5_CloseCondition "$${SETFILE}" /opt/advanced/ea-input.mqh
      BT_DEST: /opt/_results/EURUSD
  MA15_CloseCondition:
    command: run_backtest -v
    build:
      context: ../../..
      target: eurusd-2018
    image: ea31337:eurusd-2018
    volumes:
    - ./sets:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results/EURUSD:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SETFILE: /opt/sets/EURUSD/EA31337-MA15_CloseCondition.set
      TEST_REPORT_NAME: EA31337-MA15_CloseCondition
      SET_PARAMS: MA15_CloseCondition
      RUN_ON_SUCCESS: input_copy MA15_CloseCondition "$${SETFILE}" /opt/advanced/ea-input.mqh
      BT_DEST: /opt/_results/EURUSD
  MA30_CloseCondition:
    command: run_backtest -v
    build:
      context: ../../..
      target: eurusd-2018
    image: ea31337:eurusd-2018
    volumes:
    - ./sets:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results/EURUSD:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SETFILE: /opt/sets/EURUSD/EA31337-MA30_CloseCondition.set
      TEST_REPORT_NAME: EA31337-MA30_CloseCondition
      SET_PARAMS: MA30_CloseCondition
      RUN_ON_SUCCESS: input_copy MA30_CloseCondition "$${SETFILE}" /opt/advanced/ea-input.mqh
      BT_DEST: /opt/_results/EURUSD
