version: '3.4'
services:
  Bands1_OpenCondition1:
    command: run_backtest -v
    build:
      context: ../../..
      target: eurusd-2018
    image: ea31337:eurusd-2018
    volumes:
    - ./sets:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results/EURUSD:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SETFILE: /opt/sets/EURUSD/EA31337-Bands1_OpenCondition1.set
      TEST_REPORT_NAME: EA31337-Bands1_OpenCondition1
      SET_PARAMS: Bands1_OpenCondition1
      RUN_ON_SUCCESS: input_copy Bands1_OpenCondition1 "$${SETFILE}" /opt/advanced/ea-input.mqh
      BT_DEST: /opt/_results/EURUSD
  Bands5_OpenCondition1:
    command: run_backtest -v
    build:
      context: ../../..
      target: eurusd-2018
    image: ea31337:eurusd-2018
    volumes:
    - ./sets:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results/EURUSD:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SETFILE: /opt/sets/EURUSD/EA31337-Bands5_OpenCondition1.set
      TEST_REPORT_NAME: EA31337-Bands5_OpenCondition1
      SET_PARAMS: Bands5_OpenCondition1
      RUN_ON_SUCCESS: input_copy Bands5_OpenCondition1 "$${SETFILE}" /opt/advanced/ea-input.mqh
      BT_DEST: /opt/_results/EURUSD
  Bands15_OpenCondition1:
    command: run_backtest -v
    build:
      context: ../../..
      target: eurusd-2018
    image: ea31337:eurusd-2018
    volumes:
    - ./sets:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results/EURUSD:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SETFILE: /opt/sets/EURUSD/EA31337-Bands15_OpenCondition1.set
      TEST_REPORT_NAME: EA31337-Bands15_OpenCondition1
      SET_PARAMS: Bands15_OpenCondition1
      RUN_ON_SUCCESS: input_copy Bands15_OpenCondition1 "$${SETFILE}" /opt/advanced/ea-input.mqh
      BT_DEST: /opt/_results/EURUSD
  Bands30_OpenCondition1:
    command: run_backtest -v
    build:
      context: ../../..
      target: eurusd-2018
    image: ea31337:eurusd-2018
    volumes:
    - ./sets:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results/EURUSD:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SETFILE: /opt/sets/EURUSD/EA31337-Bands30_OpenCondition1.set
      TEST_REPORT_NAME: EA31337-Bands30_OpenCondition1
      SET_PARAMS: Bands30_OpenCondition1
      RUN_ON_SUCCESS: input_copy Bands30_OpenCondition1 "$${SETFILE}" /opt/advanced/ea-input.mqh
      BT_DEST: /opt/_results/EURUSD
  Bands1_OpenCondition2:
    command: run_backtest -v
    build:
      context: ../../..
      target: eurusd-2018
    image: ea31337:eurusd-2018
    volumes:
    - ./sets:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results/EURUSD:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SETFILE: /opt/sets/EURUSD/EA31337-Bands1_OpenCondition2.set
      TEST_REPORT_NAME: EA31337-Bands1_OpenCondition2
      SET_PARAMS: Bands1_OpenCondition2
      RUN_ON_SUCCESS: input_copy Bands1_OpenCondition2 "$${SETFILE}" /opt/advanced/ea-input.mqh
      BT_DEST: /opt/_results/EURUSD
  Bands5_OpenCondition2:
    command: run_backtest -v
    build:
      context: ../../..
      target: eurusd-2018
    image: ea31337:eurusd-2018
    volumes:
    - ./sets:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results/EURUSD:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SETFILE: /opt/sets/EURUSD/EA31337-Bands5_OpenCondition2.set
      TEST_REPORT_NAME: EA31337-Bands5_OpenCondition2
      SET_PARAMS: Bands5_OpenCondition2
      RUN_ON_SUCCESS: input_copy Bands5_OpenCondition2 "$${SETFILE}" /opt/advanced/ea-input.mqh
      BT_DEST: /opt/_results/EURUSD
  Bands15_OpenCondition2:
    command: run_backtest -v
    build:
      context: ../../..
      target: eurusd-2018
    image: ea31337:eurusd-2018
    volumes:
    - ./sets:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results/EURUSD:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SETFILE: /opt/sets/EURUSD/EA31337-Bands15_OpenCondition2.set
      TEST_REPORT_NAME: EA31337-Bands15_OpenCondition2
      SET_PARAMS: Bands15_OpenCondition2
      RUN_ON_SUCCESS: input_copy Bands15_OpenCondition2 "$${SETFILE}" /opt/advanced/ea-input.mqh
      BT_DEST: /opt/_results/EURUSD
  Bands30_OpenCondition2:
    command: run_backtest -v
    build:
      context: ../../..
      target: eurusd-2018
    image: ea31337:eurusd-2018
    volumes:
    - ./sets:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results/EURUSD:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SETFILE: /opt/sets/EURUSD/EA31337-Bands30_OpenCondition2.set
      TEST_REPORT_NAME: EA31337-Bands30_OpenCondition2
      SET_PARAMS: Bands30_OpenCondition2
      RUN_ON_SUCCESS: input_copy Bands30_OpenCondition2 "$${SETFILE}" /opt/advanced/ea-input.mqh
      BT_DEST: /opt/_results/EURUSD
