version: '3.4'
services:
  RSI1_CloseCondition:
    command: run_backtest -v
    build:
      context: ../../..
      target: eurusd-2018
    image: ea31337:eurusd-2018
    volumes:
    - ./sets:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results/EURUSD:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SETFILE: /opt/sets/EURUSD/EA31337-RSI1_CloseCondition.set
      TEST_REPORT_NAME: EA31337-RSI1_CloseCondition
      SET_PARAMS: RSI1_CloseCondition
      RUN_ON_SUCCESS: input_copy RSI1_CloseCondition "$${SETFILE}" /opt/advanced/ea-input.mqh
      BT_DEST: /opt/_results/EURUSD
  RSI5_CloseCondition:
    command: run_backtest -v
    build:
      context: ../../..
      target: eurusd-2018
    image: ea31337:eurusd-2018
    volumes:
    - ./sets:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results/EURUSD:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SETFILE: /opt/sets/EURUSD/EA31337-RSI5_CloseCondition.set
      TEST_REPORT_NAME: EA31337-RSI5_CloseCondition
      SET_PARAMS: RSI5_CloseCondition
      RUN_ON_SUCCESS: input_copy RSI5_CloseCondition "$${SETFILE}" /opt/advanced/ea-input.mqh
      BT_DEST: /opt/_results/EURUSD
  RSI15_CloseCondition:
    command: run_backtest -v
    build:
      context: ../../..
      target: eurusd-2018
    image: ea31337:eurusd-2018
    volumes:
    - ./sets:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results/EURUSD:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SETFILE: /opt/sets/EURUSD/EA31337-RSI15_CloseCondition.set
      TEST_REPORT_NAME: EA31337-RSI15_CloseCondition
      SET_PARAMS: RSI15_CloseCondition
      RUN_ON_SUCCESS: input_copy RSI15_CloseCondition "$${SETFILE}" /opt/advanced/ea-input.mqh
      BT_DEST: /opt/_results/EURUSD
  RSI30_CloseCondition:
    command: run_backtest -v
    build:
      context: ../../..
      target: eurusd-2018
    image: ea31337:eurusd-2018
    volumes:
    - ./sets:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results/EURUSD:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SETFILE: /opt/sets/EURUSD/EA31337-RSI30_CloseCondition.set
      TEST_REPORT_NAME: EA31337-RSI30_CloseCondition
      SET_PARAMS: RSI30_CloseCondition
      RUN_ON_SUCCESS: input_copy RSI30_CloseCondition "$${SETFILE}" /opt/advanced/ea-input.mqh
      BT_DEST: /opt/_results/EURUSD
