version: '3.4'
services:
  WPR1_OpenCondition1:
    command: run_backtest -v
    build:
      context: ../../..
      target: eurusd-2018
    image: ea31337:eurusd-2018
    volumes:
    - ./sets:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results/EURUSD:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SETFILE: /opt/sets/EURUSD/EA31337-WPR1_OpenCondition1.set
      TEST_REPORT_NAME: EA31337-WPR1_OpenCondition1
      SET_PARAMS: WPR1_OpenCondition1
      RUN_ON_SUCCESS: input_copy WPR1_OpenCondition1 "$${SETFILE}" /opt/advanced/ea-input.mqh
      BT_DEST: /opt/_results/EURUSD
  WPR5_OpenCondition1:
    command: run_backtest -v
    build:
      context: ../../..
      target: eurusd-2018
    image: ea31337:eurusd-2018
    volumes:
    - ./sets:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results/EURUSD:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SETFILE: /opt/sets/EURUSD/EA31337-WPR5_OpenCondition1.set
      TEST_REPORT_NAME: EA31337-WPR5_OpenCondition1
      SET_PARAMS: WPR5_OpenCondition1
      RUN_ON_SUCCESS: input_copy WPR5_OpenCondition1 "$${SETFILE}" /opt/advanced/ea-input.mqh
      BT_DEST: /opt/_results/EURUSD
  WPR15_OpenCondition1:
    command: run_backtest -v
    build:
      context: ../../..
      target: eurusd-2018
    image: ea31337:eurusd-2018
    volumes:
    - ./sets:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results/EURUSD:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SETFILE: /opt/sets/EURUSD/EA31337-WPR15_OpenCondition1.set
      TEST_REPORT_NAME: EA31337-WPR15_OpenCondition1
      SET_PARAMS: WPR15_OpenCondition1
      RUN_ON_SUCCESS: input_copy WPR15_OpenCondition1 "$${SETFILE}" /opt/advanced/ea-input.mqh
      BT_DEST: /opt/_results/EURUSD
  WPR30_OpenCondition1:
    command: run_backtest -v
    build:
      context: ../../..
      target: eurusd-2018
    image: ea31337:eurusd-2018
    volumes:
    - ./sets:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results/EURUSD:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SETFILE: /opt/sets/EURUSD/EA31337-WPR30_OpenCondition1.set
      TEST_REPORT_NAME: EA31337-WPR30_OpenCondition1
      SET_PARAMS: WPR30_OpenCondition1
      RUN_ON_SUCCESS: input_copy WPR30_OpenCondition1 "$${SETFILE}" /opt/advanced/ea-input.mqh
      BT_DEST: /opt/_results/EURUSD
  WPR1_OpenCondition2:
    command: run_backtest -v
    build:
      context: ../../..
      target: eurusd-2018
    image: ea31337:eurusd-2018
    volumes:
    - ./sets:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results/EURUSD:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SETFILE: /opt/sets/EURUSD/EA31337-WPR1_OpenCondition2.set
      TEST_REPORT_NAME: EA31337-WPR1_OpenCondition2
      SET_PARAMS: WPR1_OpenCondition2
      RUN_ON_SUCCESS: input_copy WPR1_OpenCondition2 "$${SETFILE}" /opt/advanced/ea-input.mqh
      BT_DEST: /opt/_results/EURUSD
  WPR5_OpenCondition2:
    command: run_backtest -v
    build:
      context: ../../..
      target: eurusd-2018
    image: ea31337:eurusd-2018
    volumes:
    - ./sets:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results/EURUSD:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SETFILE: /opt/sets/EURUSD/EA31337-WPR5_OpenCondition2.set
      TEST_REPORT_NAME: EA31337-WPR5_OpenCondition2
      SET_PARAMS: WPR5_OpenCondition2
      RUN_ON_SUCCESS: input_copy WPR5_OpenCondition2 "$${SETFILE}" /opt/advanced/ea-input.mqh
      BT_DEST: /opt/_results/EURUSD
  WPR15_OpenCondition2:
    command: run_backtest -v
    build:
      context: ../../..
      target: eurusd-2018
    image: ea31337:eurusd-2018
    volumes:
    - ./sets:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results/EURUSD:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SETFILE: /opt/sets/EURUSD/EA31337-WPR15_OpenCondition2.set
      TEST_REPORT_NAME: EA31337-WPR15_OpenCondition2
      SET_PARAMS: WPR15_OpenCondition2
      RUN_ON_SUCCESS: input_copy WPR15_OpenCondition2 "$${SETFILE}" /opt/advanced/ea-input.mqh
      BT_DEST: /opt/_results/EURUSD
  WPR30_OpenCondition2:
    command: run_backtest -v
    build:
      context: ../../..
      target: eurusd-2018
    image: ea31337:eurusd-2018
    volumes:
    - ./sets:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results/EURUSD:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SETFILE: /opt/sets/EURUSD/EA31337-WPR30_OpenCondition2.set
      TEST_REPORT_NAME: EA31337-WPR30_OpenCondition2
      SET_PARAMS: WPR30_OpenCondition2
      RUN_ON_SUCCESS: input_copy WPR30_OpenCondition2 "$${SETFILE}" /opt/advanced/ea-input.mqh
      BT_DEST: /opt/_results/EURUSD
