version: '3.4'
services:
  DeMarker1_CloseCondition:
    command: run_backtest -v
    build:
      context: ../../..
      target: eurusd-2018
    image: ea31337:eurusd-2018
    volumes:
    - ./sets:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results/EURUSD:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SETFILE: /opt/sets/EURUSD/EA31337-DeMarker1_CloseCondition.set
      TEST_REPORT_NAME: EA31337-DeMarker1_CloseCondition
      SET_PARAMS: DeMarker1_CloseCondition
      RUN_ON_SUCCESS: input_copy DeMarker1_CloseCondition "$${SETFILE}" /opt/advanced/ea-input.mqh
      BT_DEST: /opt/_results/EURUSD
  DeMarker5_CloseCondition:
    command: run_backtest -v
    build:
      context: ../../..
      target: eurusd-2018
    image: ea31337:eurusd-2018
    volumes:
    - ./sets:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results/EURUSD:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SETFILE: /opt/sets/EURUSD/EA31337-DeMarker5_CloseCondition.set
      TEST_REPORT_NAME: EA31337-DeMarker5_CloseCondition
      SET_PARAMS: DeMarker5_CloseCondition
      RUN_ON_SUCCESS: input_copy DeMarker5_CloseCondition "$${SETFILE}" /opt/advanced/ea-input.mqh
      BT_DEST: /opt/_results/EURUSD
  DeMarker15_CloseCondition:
    command: run_backtest -v
    build:
      context: ../../..
      target: eurusd-2018
    image: ea31337:eurusd-2018
    volumes:
    - ./sets:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results/EURUSD:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SETFILE: /opt/sets/EURUSD/EA31337-DeMarker15_CloseCondition.set
      TEST_REPORT_NAME: EA31337-DeMarker15_CloseCondition
      SET_PARAMS: DeMarker15_CloseCondition
      RUN_ON_SUCCESS: input_copy DeMarker15_CloseCondition "$${SETFILE}" /opt/advanced/ea-input.mqh
      BT_DEST: /opt/_results/EURUSD
  DeMarker30_CloseCondition:
    command: run_backtest -v
    build:
      context: ../../..
      target: eurusd-2018
    image: ea31337:eurusd-2018
    volumes:
    - ./sets:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results/EURUSD:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SETFILE: /opt/sets/EURUSD/EA31337-DeMarker30_CloseCondition.set
      TEST_REPORT_NAME: EA31337-DeMarker30_CloseCondition
      SET_PARAMS: DeMarker30_CloseCondition
      RUN_ON_SUCCESS: input_copy DeMarker30_CloseCondition "$${SETFILE}" /opt/advanced/ea-input.mqh
      BT_DEST: /opt/_results/EURUSD
