version: '3.4'
services:
  Bands1_CloseCondition:
    command: run_backtest -v
    build:
      context: ../../..
      target: eurusd-2018
    image: ea31337:eurusd-2018
    volumes:
    - ./sets:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results/EURUSD:rw
    env_file: ../../../EA-Tester.ini
    environment:
      BT_MONTHS: 1-2
      SETFILE: /opt/sets/EURUSD/EA31337-Bands1_CloseCondition.set
      TEST_REPORT_NAME: EA31337-Bands1_CloseCondition
      SET_PARAMS: Bands1_CloseCondition
      RUN_ON_SUCCESS: input_copy Bands1_CloseCondition "$${SETFILE}" /opt/advanced/ea-input.mqh
      BT_DEST: /opt/_results/EURUSD
  Bands5_CloseCondition:
    command: run_backtest -v
    build:
      context: ../../..
      target: eurusd-2018
    image: ea31337:eurusd-2018
    volumes:
    - ./sets:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results/EURUSD:rw
    env_file: ../../../EA-Tester.ini
    environment:
      BT_MONTHS: 1-2
      SETFILE: /opt/sets/EURUSD/EA31337-Bands5_CloseCondition.set
      TEST_REPORT_NAME: EA31337-Bands5_CloseCondition
      SET_PARAMS: Bands5_CloseCondition
      RUN_ON_SUCCESS: input_copy Bands5_CloseCondition "$${SETFILE}" /opt/advanced/ea-input.mqh
      BT_DEST: /opt/_results/EURUSD
  Bands15_CloseCondition:
    command: run_backtest -v
    build:
      context: ../../..
      target: eurusd-2018
    image: ea31337:eurusd-2018
    volumes:
    - ./sets:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results/EURUSD:rw
    env_file: ../../../EA-Tester.ini
    environment:
      BT_MONTHS: 1-2
      SETFILE: /opt/sets/EURUSD/EA31337-Bands15_CloseCondition.set
      TEST_REPORT_NAME: EA31337-Bands15_CloseCondition
      SET_PARAMS: Bands15_CloseCondition
      RUN_ON_SUCCESS: input_copy Bands15_CloseCondition "$${SETFILE}" /opt/advanced/ea-input.mqh
      BT_DEST: /opt/_results/EURUSD
  Bands30_CloseCondition:
    command: run_backtest -v
    build:
      context: ../../..
      target: eurusd-2018
    image: ea31337:eurusd-2018
    volumes:
    - ./sets:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results/EURUSD:rw
    env_file: ../../../EA-Tester.ini
    environment:
      BT_MONTHS: 1-2
      SETFILE: /opt/sets/EURUSD/EA31337-Bands30_CloseCondition.set
      TEST_REPORT_NAME: EA31337-Bands30_CloseCondition
      SET_PARAMS: Bands30_CloseCondition
      RUN_ON_SUCCESS: input_copy Bands30_CloseCondition "$${SETFILE}" /opt/advanced/ea-input.mqh
      BT_DEST: /opt/_results/EURUSD
