version: '3.4'
services:
  WPR1_CloseCondition:
    command: run_backtest -v
    build:
      context: ../../..
      target: eurusd-2018
    image: ea31337:eurusd-2018
    volumes:
    - ./sets:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results/EURUSD:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SETFILE: /opt/sets/EURUSD/EA31337-WPR1_CloseCondition.set
      TEST_REPORT_NAME: EA31337-WPR1_CloseCondition
      SET_PARAMS: WPR1_CloseCondition
      RUN_ON_SUCCESS: input_copy WPR1_CloseCondition "$${SETFILE}" /opt/advanced/ea-input.mqh
      BT_DEST: /opt/_results/EURUSD
  WPR5_CloseCondition:
    command: run_backtest -v
    build:
      context: ../../..
      target: eurusd-2018
    image: ea31337:eurusd-2018
    volumes:
    - ./sets:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results/EURUSD:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SETFILE: /opt/sets/EURUSD/EA31337-WPR5_CloseCondition.set
      TEST_REPORT_NAME: EA31337-WPR5_CloseCondition
      SET_PARAMS: WPR5_CloseCondition
      RUN_ON_SUCCESS: input_copy WPR5_CloseCondition "$${SETFILE}" /opt/advanced/ea-input.mqh
      BT_DEST: /opt/_results/EURUSD
  WPR15_CloseCondition:
    command: run_backtest -v
    build:
      context: ../../..
      target: eurusd-2018
    image: ea31337:eurusd-2018
    volumes:
    - ./sets:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results/EURUSD:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SETFILE: /opt/sets/EURUSD/EA31337-WPR15_CloseCondition.set
      TEST_REPORT_NAME: EA31337-WPR15_CloseCondition
      SET_PARAMS: WPR15_CloseCondition
      RUN_ON_SUCCESS: input_copy WPR15_CloseCondition "$${SETFILE}" /opt/advanced/ea-input.mqh
      BT_DEST: /opt/_results/EURUSD
  WPR30_CloseCondition:
    command: run_backtest -v
    build:
      context: ../../..
      target: eurusd-2018
    image: ea31337:eurusd-2018
    volumes:
    - ./sets:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results/EURUSD:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SETFILE: /opt/sets/EURUSD/EA31337-WPR30_CloseCondition.set
      TEST_REPORT_NAME: EA31337-WPR30_CloseCondition
      SET_PARAMS: WPR30_CloseCondition
      RUN_ON_SUCCESS: input_copy WPR30_CloseCondition "$${SETFILE}" /opt/advanced/ea-input.mqh
      BT_DEST: /opt/_results/EURUSD
